spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pezzbdwepaoztfdvypcv
spring.datasource.password=8vywdLxLpI7NrPr9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

woocommerce.base-url=https://kanogapurpletea.com
woocommerce.consumer-key=ck_72b21e835600e50a5fa8cc43bc4575cd4db3c1fb
woocommerce.consumer-secret= cs_434aa5dc6887c9d202a31a230ff278c3218a6704
woocommerce.webhook.secret=  4'z!6Ghl3AAh