spring.datasource.url=jdbc:postgresql://db.pezzbdwepaoztfdvypcv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=ch53H63rXYQoCJ4xv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

